<a href="https://colab.research.google.com/github/areola-joshua/Force-2020-Machine-Learning-competition/blob/master/first_pytorch_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
x = torch.rand(1,2)

In [5]:
x

tensor([[0.5579, 0.1110]])

In [6]:
x = torch.empty(2,2,2)
x

tensor([[[1.3170e+35, 4.5822e-41],
         [1.3170e+35, 4.5822e-41]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])

In [9]:
y = torch.zeros(2,2)
y

tensor([[0., 0.],
        [0., 0.]])

In [10]:
type(y)

torch.Tensor

In [12]:
c = torch.ones(3,2, dtype=torch.float16)
print(c, c.dtype)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float16) torch.float16


In [13]:
c.size()

torch.Size([3, 2])

In [14]:
s = torch.tensor([2.5, 0.1])
s

tensor([2.5000, 0.1000])

In [ ]:
x = torch.rand()